general {
    lock_cmd = noctalia msg session lock     # Main lock command
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 300                                # 5 minutes
    on-timeout = loginctl lock-session           # Triggers Noctalia lockscreen
}

listener {
        timeout = 330                            # 5.5 minutes
        on-timeout = hyprctl dispatch dpms off   # turn monitor off
        on-resume = hyprctl dispatch dpms on
    }

listener {
    timeout = 1800                                # 30 min.
    on-timeout = systemctl suspend                # suspend pc
}
