# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Windowrules Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Workspaces Rules https://wiki.hyprland.org/Configuring/Workspace-Rules/ #
workspace = 1, name:Browser, gapsout:5, gapsin:3, persistent:true
workspace = 2, name:Terminal, gapsout:5, gapsin:3, persistent:true
workspace = 3, name:Games, gapsout:5, gapsin:3, persistent:true
workspace = 4, name:Social, gapsout:5, gapsin:3, persistent:true
workspace = 5, name:Misc, gapsout:5, gapsin:3, persistent:true
workspace = 10, name:Media, gapsout:5, gapsin:3, persistent:true

# Windows Rules https://wiki.hyprland.org/Configuring/Window-Rules/ #
windowrule = workspace 1, maximize on, match:class ^(app.zen_browser.zen)$
windowrule = workspace 2, maximize on, match:class ^(com.mitchellh.ghostty|kitty|org.wezfurlong.wezterm)$
windowrule = workspace 3, maximize on, match:class ^(steam|lutris|heroic|faugus-launcher)$
windowrule = workspace 4, maximize on, match:class ^(vesktop)$
windowrule = workspace 10, maximize on, match:class ^(Spotify)$
# windowrule = workspace 5, class:^(.+)$
# Float Necessary Windows
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)
windowrule = float on, match:class ^()$, match:title ^(Picture in picture)$
windowrule = float on, match:class ^()$, match:title ^(Save File)$
windowrule = float on, match:class ^()$, match:title ^(Open File)$
windowrule = float on, match:class ^(LibreWolf)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
windowrule = float on, match:class ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$
windowrule = float on, match:class ^(CachyOSHello)$
windowrule = float on, match:class ^(zenity)$
windowrule = float on, match:class ^()$, match:title ^(Steam - Self Updater)$
# Increase the opacity
windowrule = opacity 0.92, match:class ^(thunar|nemo)$
windowrule = opacity 0.96, match:class ^(discord|armcord|webcord)$
windowrule = opacity 0.95, match:title ^(QQ|Telegram)$
windowrule = opacity 0.95, match:title ^(NetEase Cloud Music Gtk4)$
# General window rules
windowrule = float on, size 960 540, move ((monitor_w*0.25)-), match:title ^(Picture-in-Picture)$
windowrule = float on, move ((monitor_w*0.25)-), size 960 540, match:title ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
windowrule = pin on, match:title ^(danmufloat)$
windowrule = rounding 5, match:title ^(danmufloat|termfloat)$
windowrule = animation slide right, match:class ^(kitty|Alacritty)$
windowrule = no_blur on, match:class ^(org.mozilla.firefox)$
# Decorations related to floating windows on workspaces 1 to 10
windowrule = border_size 2, border_color $cachylblue, rounding 8, match:float 1, match:workspace w[fv1-10]
# Decorations related to tiling windows on workspaces 1 to 10
windowrule = border_size 3, rounding 4, match:float 0, match:workspace f[1-10]
# Windows Rules End #

# Layers Rules #
layerrule = animation slide top, match:namespace logout_dialog
# layerrule = animation popin 50%, waybar
layerrule = animation slide down, match:namespace waybar
layerrule = animation fade 50%, match:namespace wallpaper
# Layers Rules End #
